### ISSUE TITLE
minisom 2.1.6 broken on Python 3.5.6

### ISSUE THREAD

**Issue by gykovacs** [JustGlowing/minisom#34]
Hi All,

I just installed minisom 2.1.6 from the PyPi repository into a fresh Anaconda Python 3.5.6 environment on a Kubuntu 19.04 box and run into the following issue:

```
(base) gykovacs@gykovacs-desktop:~$ conda activate p35
(p35) gykovacs@gykovacs-desktop:~$ python --version
Python 3.5.6 :: Anaconda, Inc.

(p35) gykovacs@gykovacs-desktop:~$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

(p35) gykovacs@gykovacs-desktop:~$ pip install minisom
Collecting minisom
Installing collected packages: minisom
Successfully installed minisom-2.1.6
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(p35) gykovacs@gykovacs-desktop:~$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import minisom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gykovacs/anaconda3/envs/p35/lib/python3.5/site-packages/minisom.py", line 23
    progress = f'\r [ {0:{len(str(m))}} / {m} ] {0:3.0f}% - ? it/s'
                                                                  ^
SyntaxError: invalid syntax
>>> 
```

**Comment by JustGlowing** [comment]
Hi there, you need python 3.6 to run minisom.

**Comment by gykovacs** [comment]
Thanks for the quick response!

**Comment by JustGlowing** [comment]
hi @gykovacs, I (partially) restored compatibility with older versions of Python. If you pull from master you'll be able to use Minisom with Python3.5.

**Comment by gykovacs** [comment]
Thanks @JustGlowing! Is this restoration temporary, or do you plan to go on and keep compatibility with Python3.5 until major packages like scikit-learn support it?

**Comment by JustGlowing** [comment]
Yes I will, it seems that the only thing that broke compatibility was the introduction of f-strings and I removed them. Please report errors if you get any.

**Comment by gykovacs** [comment]
Cool, thanks!
